### ISSUE TITLE
OSError when loading roberta-base tokenizer

### ISSUE THREAD

**Issue by Elvinky** [OpenRobotLab/EmbodiedScan#11]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.58
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0
OpenCV: 4.9.0
MMEngine: 0.10.3
MMDetection: 3.3.0+a69213d

### Reproduces the problem - code sample

from transformers import RobertaTokenizerFast
tokenizer = RobertaTokenizerFast.from_pretrained('roberta-base')

### Reproduces the problem - command or script

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7;export MASTER_ADDR=127.0.0.1;export RANK=0;export WORLD_SIZE=1;export MASTER_PORT=29320;python tools/train.py configs/grounding/mv-grounding_8xb12_embodiedscan-vg-9dof.py --work-dir=work_dirs/mv-3dvg --launcher="pytorch"

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()                                    
  File "tools/train.py", line 122, in main
    runner = Runner.from_cfg(cfg)                                     
  File "/data/home/kye/miniconda3/envs/embodiedscan/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462,
in from_cfg                            
    runner = cls(                                                  
  File "/data/home/kye/miniconda3/envs/embodiedscan/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429,
in __init__ 
    self.model = self.build_model(model)
  File "/data/home/kye/miniconda3/envs/embodiedscan/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836,
in build_model          
    model = MODELS.build(model)                               
  File "/data/home/kye/miniconda3/envs/embodiedscan/lib/python3.8/site-packages/mmengine/registry/registry.py", line 5
70, in build                                                              
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/data/home/kye/miniconda3/envs/embodiedscan/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
 line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/data/home/kye/miniconda3/envs/embodiedscan/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
 line 121, in build_from_cfg                                                      
    obj = obj_cls(**args)  # type: ignore  
  File "/data/home/kye/projects/cvpr2024challenge/visual_grounding/EmbodiedScan/embodiedscan/models/detectors/sparse_f
eatfusion_grounder.py", line 145, in __init__
    self._init_layers()
  File "/data/home/kye/projects/cvpr2024challenge/visual_grounding/EmbodiedScan/embodiedscan/models/detectors/sparse_f
eatfusion_grounder.py", line 151, in _init_layers
    self.tokenizer = RobertaTokenizerFast.from_pretrained(t_type)
  File "/data/home/kye/miniconda3/envs/embodiedscan/lib/python3.8/site-packages/transformers/tokenization_utils_base.p
y", line 2032, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'roberta-base'. If you were trying to load it from 'https://huggingface.co/models',
make sure you don't have a local directory with the same name. Otherwise, make sure 'roberta-base' is the correct path
 to a directory containing all relevant files for a RobertaTokenizerFast tokenizer.

**Comment by Elvinky** [comment]
The issue was due to not being logged into the huggingface-cli. After logging in, I was able to download normally.

**Comment by mrsempress** [comment]
Hello, can you help me? What are the specific operations for this error? Since I am new to this field and don’t know how to use it, the loading weight on the network is the local weight. I have pip installed huggingface-cli and logged in to add the token, but it still prompts the same error.
