### ISSUE TITLE
[Docs] What type of data in Matterport3D do we need to download?

### ISSUE THREAD

**Issue by RongkunYang** [OpenRobotLab/EmbodiedScan#12]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

The full matterport3D dataset is very large, may I ask what type of data do we need to download?

**Comment by mxh1999** [comment]
For running, you will need the **matterport_color_images** and **matterport_depth_images**. These are necessary inputs for the process.

For visualization, you can use the **matterport_mesh**, **house_segmentations**, and **region_segmentations**. These provide visual representations.

For debugging, you can download the **cameras**, **matterport_camera_poses**, and **matterport_camera_poses**. Note that the annotation files already include extrinsic and intrinsic information, but it can be convenient to download them separately for debugging purposes.

If you have limited space, the model can still work properly with just the **matterport_color_images** and **matterport_depth_images**.

**Comment by RongkunYang** [comment]
OK, thank you for your fast response, I'll try it.

**Comment by jjlinghu** [comment]
Hi! If I just want to debug, do I also have to download these three datasets and convert them in addition to EmbodiedScan.

**Comment by mxh1999** [comment]
> Hi! If I just want to debug, do I also have to download these three datasets and convert them in addition to EmbodiedScan.

Yes
