### ISSUE TITLE
[Docs] Request more detailed dataset structure.

### ISSUE THREAD

**Issue by EricLee0224** [OpenRobotLab/EmbodiedScan#15]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

Awesome work!

Is it possible for the team to provide more detail on the structure of the external datasets (Scannet, 3RScan and Matterport3D)? Since the full versions of the individual datasets are very large, we would like to download only part of the datasets based on EmbodiedScan's actual needs.

Thanks!

**Comment by mxh1999** [comment]
For Scannet, you can find the data structure [Here](https://github.com/ScanNet/ScanNet?tab=readme-ov-file#data-organization). In this structure, the **<scanId>.sens** file is required as the model input, while **<scanId>_vh_clean.ply** is used for visualization purposes.

For 3RScan, the data structure can be found [Here](https://github.com/WaldJohannaU/3RScan?tab=readme-ov-file#data-organization-and-format). In this structure, the **sequence.zip** file is necessary as the model input, and for visualization, you would utilize **mesh.refined.v2.obj**, **mesh.refined.mtl**, and **mesh.refined_0.png**.

For Matterport3D, refer to #12
