### ISSUE TITLE
Can you make it more clear about the dataset we need to prepare?

### ISSUE THREAD

**Issue by goodstudent9** [OpenRobotLab/EmbodiedScan#18]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

When you talk about the dataset that is used such as scannet, mp3d and so on, it is better if you can provide us clear guide that can tell us which part of dataset we need. You can give me the download command such as --task habitat so that we can know. 
Or if we need to download them entirely?

**Comment by mxh1999** [comment]
See #15

**Comment by Tai-Wang** [comment]
Close due to inactivity. Please feel free to post new questions or reopen this issue if necessary.
