### ISSUE TITLE
[Docs] How to run the demo ?

### ISSUE THREAD

**Issue by BetterYimi** [OpenRobotLab/EmbodiedScan#21]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

I used 'configs/detection/mv-det3d_8xb4_embodiedscan-3d-284class-9dof.py' , 'mv-3ddet.pth' provided by you, and your simple dataset office to test demo.ipynb. but I can only get one picture of the results, the length of results in `results = model.test_step(collate_data)` is 1

**Comment by 4mm7** [comment]
I  have encountered an issue similar to one you previously experienced. I am reaching out to inquire about how you resolved it.Could you please share any insights or solutions you found for the issue?

**Comment by 4mm7** [comment]
@BetterYimi Excuse me, I encountered a similar problem to #21 when running the demo.py script. Upon inspecting the model output, I noticed that len(results) is 1, which resulted in only one image being visualized, with the boxes stacked on top of each other. However, that issue has already been closed. I'm unsure how to resolve this situation.If you can provide assistance, that would be great.

**Comment by BetterYimi** [comment]
@4mm7  我是简单将代码中的`len(results)`改为了`1-len(n_frames)`，同时将`boxes, labels = nms_filter(results[i].pred_instances_3d)`改为了`boxes, labels = nms_filter(results[0].pred_instances_3d)`

**Comment by xiaolu-luu** [comment]
> @4mm7 我是简单将代码中的`len(results)`改为了`1-len(n_frames)`，同时将`boxes, labels = nms_filter(results[i].pred_instances_3d)`改为了`boxes, labels = nms_filter(results[0].pred_instances_3d)`

可以详细说一下如何操作吗？哪里的len(results)改为了1-len(n_frames)，感谢！！！
