### ISSUE TITLE
[Feature] Any plan to support 3D instance segmentation

### ISSUE THREAD

**Issue by RayYoh** [OpenRobotLab/EmbodiedScan#25]
### What is the feature?

Hi, authors. Thanks for your great work and make it available. In 3D scene understanding, instance segmentation is also a common task for the embodied agent. So, I'd like to ask whether there are plans to make EmbodiedScan support this task.

**Comment by mxh1999** [comment]
To support 3D instance segmentations, we need additional point-level annotations.
We will consider it in the future work.

**Comment by RayYoh** [comment]
> To support 3D instance segmentations, we need additional point-level annotations. We will consider it in the future work.

Got that, thanks for your reply.
