### ISSUE TITLE
about training time

### ISSUE THREAD

**Issue by Outlying3720** [OpenRobotLab/EmbodiedScan#34]
### What is the feature?

Hi, thanks for your nice work and open code! 
I want to know how many hours did you train on what kind of gpus configurations?
Thanks!

**Comment by Tai-Wang** [comment]
It takes about 8 hours to train the multi-view 3D visual grounding baseline and 12 hours to train the 3D detection baseline. Please refer to our logs provided [here](https://github.com/OpenRobotLab/EmbodiedScan?tab=readme-ov-file#benchmark) for more details.

**Comment by Outlying3720** [comment]
Thanks!
