### ISSUE TITLE
[Docs] The ckpt and log links on the README seem to be unavaliable

### ISSUE THREAD

**Issue by iris0329** [OpenRobotLab/EmbodiedScan#41]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

The ckpt and log links on the README seem to be unavaliable; they were still available last week. 

I am not sure it's the case on my side, but I can't open it even if I switch to another network.

**Comment by iris0329** [comment]
Thank you for your reply and look forward to updating

**Comment by Tai-Wang** [comment]
The links have been updated. Please try to download them again.
