### ISSUE TITLE
[Docs] The training command for MVDET

### ISSUE THREAD

**Issue by RongkunYang** [OpenRobotLab/EmbodiedScan#47]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

In the readme.md, this doc provide the command for  training:
python tools/train.py configs/detection/mv-det3d_8xb4_embodiedscan-3d-284class-9dof.py --work-dir=work_dirs/mv-3ddet --launcher="pytorch"

But this command run get error, because the launcher="pytorch" is set for distributed training. The error is below:

"""
anaconda3/envs/embodiedscan/lib/python3.8/site-packages/mmengine/dist/utils.py", line 102, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/anaconda3/envs/embodiedscan/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
"""

It seems that the distributed training parameters are not set during training, could you please share the detail running command about this, thank you very much.

**Comment by mxh1999** [comment]
The command in `README.md` has some faults, please remove the `--launcher` parameter if you are using only one GPU for training.

We will update `README.md` soon, thanks for the report.
