### ISSUE TITLE
[Docs] Full log on the multiview grounding full setting

### ISSUE THREAD

**Issue by henryzhengr** [OpenRobotLab/EmbodiedScan#49]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

The full log for the multiview grounding full setting seems to include only logs from resumption. 
[https://download.openmmlab.com/mim-example/embodiedscan/mv-grounding-full.log](mv-grounding-full.log)

### Suggest a potential alternative/fix

Is it possible to request for the full log from the start?

**Comment by Tai-Wang** [comment]
I am sorry that the log is incomplete because the full dataset training is easy to interrupt due to large computational burden. It's hard to find the original one, so I will re-train the model with `num_queries=100` and provide the log afterward for your reference.

**Comment by henryzhengr** [comment]
Thank you! Cuz I am curious whether there's a difference between our config settings or due to experiment variance.
