### ISSUE TITLE
[Docs] Will the acc@0.25 >1. in 3DVG?

### ISSUE THREAD

**Issue by iris0329** [OpenRobotLab/EmbodiedScan#50]

**Comment by Tai-Wang** [comment]
Good observation. Each data sample of our current benchmark only contain only one gt box for grounding, so the case you mention will not happen temporarily. When evaluating the case with multiple grounding boxes, we will adjust the evaluation metric code afterward. Please stay tuned.

**Comment by Tai-Wang** [comment]
Note that `found = int(threshold.any())` can only be 0 or 1, so pred is always smaller than gt. Therefore, the accuracy is always smaller than 1.

BTW, the current metric is only suitable for the current benchmark with only one gt box. When we have multiple boxes in a data sample to ground, we will adjust the metric afterward. Please stay tuned for further updates.

**Comment by iris0329** [comment]
@Tai-Wang, thank you for the detailed response. I just found that the value of `found` only be 0 or 1.

**Comment by LZ-CH** [comment]
@Tai-Wang Hi, I noticed that when calculating the grounding indicator, the box with the top-10 score is selected as the prediction box. Why is 10 chosen instead of 1? 
`
            box_index = target_scores.argsort(dim=-1, descending=True)[:10]
            top_bbox = bboxes[box_index]

            iou = top_bbox.overlaps(top_bbox, gt_bboxes)  # (num_query, 1)
`
