### ISSUE TITLE
[Feature] Support ScanRefer or nr3d/sr3d data set in Multi-View 3D Visual Grounding Task.

### ISSUE THREAD

**Issue by LZ-CH** [OpenRobotLab/EmbodiedScan#55]
### What is the feature?

Hi, Thank you very much for your great work. Have you tried training and verifying this benchmark on scanrefer or nr3d/sr3d datasets? If so, can you publish the code that supports training and verification in other 3D-grounding datasets? This can provide great convenience for researcher to further improve and evaluate based on your benchmark in Multi-View 3D Visual Grounding Task.

**Comment by Tai-Wang** [comment]
Thanks for your suggestion. It is also important to evaluate methods on conventional 3D visual grounding benchmarks. We will consider supporting this feature here or in [Grounded 3D-LLM](https://github.com/OpenRobotLab/Grounded_3D-LLM) afterward.

**Comment by LZ-CH** [comment]
Thanks! Looking forward to your great work in the future!!!
