### ISSUE TITLE
[Bug] Why is there no generate_image_matterport3d.py? Is the post-processed data of matterport3d release?

### ISSUE THREAD

**Issue by GCChen97** [OpenRobotLab/EmbodiedScan#57]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

--

### Reproduces the problem - code sample

```python
explorer = EmbodiedScanExplorer(
	data_root={
        'scannet' : '/Data/Datasets/embodiedscan/scannet',
        '3rscan' : '/Data/Datasets/embodiedscan/3rscan',
        'matterport3d': '/Data/Datasets/embodiedscan/matterport3d',
        },
	ann_file=['/Data/Datasets/embodiedscan/embodiedscan_infos_train.pkl', '/Data/Datasets/embodiedscan/embodiedscan_infos_val.pkl'],
	verbose=True,	# print log or not
)
```

### Reproduces the problem - command or script

I ran `explorer.list_scenes()` but no matterport3d scenes appeared.

### Reproduces the problem - error message

There are only scannet scenes and 3rscan scenes

**Comment by mxh1999** [comment]
It seems that the explorer doesn't find the scene folders of matterport3d.
Could you please provide the file structure of the `data` directory?

**Comment by GCChen97** [comment]
Hi, thanks for paying attention. Below is the file structure:
|--embodiedscan
   |--......
   |--matterport3d
      |--1LXtFkjw3qL
      |--1pXnuDYAj8r
      |--......

The explorer can find 3rscan and scannet except matterport3d.

> It seems that the explorer doesn't find the scene folders of matterport3d. Could you please provide the file structure of the `data` directory?

**Comment by mxh1999** [comment]
> Hi, thanks for paying attention. Below is the file structure:
> 
> ```
> |--embodiedscan
> |   |--......
> |   |--matterport3d
> |      |--1LXtFkjw3qL
> |      |--1pXnuDYAj8r
> |      |--......
> ```
> 
> The explorer can find 3rscan and scannet except matterport3d.
> 
> > It seems that the explorer doesn't find the scene folders of matterport3d. Could you please provide the file structure of the `data` directory?

This is strange... Our data directory looks the same, but explorer works fine here.
You can add `print(dirpath)` to explorer.py after line 119 to check if the path is correct.

**Comment by GCChen97** [comment]
The path is correct. I also check it in the terminal using `ls`:
```
$ ls embodiedscan/matterport3d/

17DRP5sb8fy  aayBHfsNo7d  gTV8FGcVJC9  pa4otMbVnkk  S9hNv5qa7GM  Vvot9Ly1tCj
1LXtFkjw3qL  ac26ZMwG7aT  gxdoqLR6rwA  pLe4wQe7qrG  sKLMLpTHeUy  vyrNrziPKCB
1pXnuDYAj8r  ARNzJeq3xxb  gYvKGZ5eRqb  Pm6F8kyY3z2  SN83YJsR3w2  VzqfbhrpDEA
29hnd4uzFmX  B6ByNegPMKs  gZ6f7yhEvPG  pRbA3pwrgk9  sT4fr6TAbpF  wc2JMjhGNzB
2azQ1b91cZZ  b8cTxDM8gDG  HxpKQynjfin  PuKPg4mmafe  TbHJrupSAjP  WYY7iVyf5p8
2n8kARJN3HM  cV4RVeZvu5T  i5noydFURQK  PX4nDJXEHrG  ULsKaCPVFJR  X7HyMhZNoso
2t7WUuJeko7  D7G3Y4RVNrH  JeFG25nYj2p  q9vSo1VnCiC  uNb9QFRL6hY  x8F5xyUWy9e
5LpN3gDmAk7  D7N2EKCX4Sj  JF19kD82Mey  qoiz87JEwZ2  ur6pFq6Qu1A  XcA2TqTSSAj
5q7pvUzZiYa  dhjEzFoUFzH  jh4fc5c5qoQ  QUCTc6BB5sX  UwV83HsGsw3  YFuZgdQ5vWj
5ZKStnWn8Zo  E9uDoFAP3SH  JmbYfDe2QKZ  r1Q1Z4BcV1o  Uxmj2M2itWa  YmJkqBEsHnH
759xd9YjKW5  e9zR4mvMWw7  jtcxE69GiFV  r47D5H71a5s  V2XKFyX4ASd  yqstnuAEVhm
7y3sRwLe3Va  EDJbREhghzL  kEZ7cmS4wCh  rPc6DW4iMge  VFuaQ6m2Qom  YVUC4YcDtcY
8194nk5LbLH  EU6Fwq7SyZv  mJXqzFtmKg4  RPmz2sHmrrY  VLzqgDo317F  Z6MFQCViBuw
82sE5b5pLXE  fzynW3qQPVF  oLBMNvg9in8  rqfALeAoiTq  Vt2qJdWjCF2  ZMojNkEp431
8WUmhLawc2A  GdvgFV5R1Z5  p5wJjkQkbXX  s8pcmisQ38h  VVfe2KiqLaN  zsNo4HB9uLZ
```

> This is strange... Our data directory looks the same, but explorer works fine here. You can add `print(dirpath)` to `explorer.py` after `line 119` to check if the path is correct.

**Comment by GCChen97** [comment]
I found the problem. It was stupid. Vscode truncated the output and I didn't notice it.

**Comment by GCChen97** [comment]
BTW, is it necessary to process the matterport3d dataset like 3rscan and scannet, such as using `generate_image_matterport3d.py`?

**Comment by mxh1999** [comment]
> BTW, is it necessary to process the matterport3d dataset like 3rscan and scannet, such as using `generate_image_matterport3d.py`?

The images of scannet and 3rscan are zipped so we need to extract them. You can check your matterport3d raw data is zipped or not.
