### ISSUE TITLE
[Feature] How to access post-process camera poses?

### ISSUE THREAD

**Issue by GCChen97** [OpenRobotLab/EmbodiedScan#58]
### What is the feature?

API for accessing camera poses.
The paper introduces some post-process steps for the camera poses. How do I get access to those camera poses?

**Comment by Tai-Wang** [comment]
The camera poses are recorded in the EmbodiedScan info. Please follow the homepage README to ask for the access to our data and you can find the corresponding camera poses in the info.

**Comment by GCChen97** [comment]
Thanks for the reply. The access is simpler than what I expect.
```
explorer.data[0]['images'][0]['cam2global']
```
