### ISSUE TITLE
[Docs] seem a bug in  "nms_filter" when running demo 

### ISSUE THREAD

**Issue by aidenchn** [OpenRobotLab/EmbodiedScan#59]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

When I ran demo as the readme say, I met a bug. 

And my configs are as follows:
config file:   cont-det3d_8xb1_embodiedscan-3d-284class-9dof.py  (from your project)
weights:  cont-3ddet.pth (from your download link)
data:  openscan.zip (from your download link)
scene:  restroom

The problem seems like small 3d-boxes exists and are not filtered.
Could you help me check that it's a bug or my config is wrong. Thanks a lot and very appreciate your work.

![1720060809169](https://github.com/OpenRobotLab/EmbodiedScan/assets/24630296/315ea48d-b05c-44e6-bbb6-9874abfc5815)

**Comment by Tai-Wang** [comment]
This issue is triggered due to reasons similar to [this one](https://github.com/OpenRobotLab/EmbodiedScan/issues/40#issuecomment-2058598322). Please follow the comment and try again.

**Comment by aidenchn** [comment]
Thanks a lot. Very appriciate your work！

**Comment by chinagalaxy2002** [comment]
> This issue is triggered due to reasons similar to [this one](https://github.com/OpenRobotLab/EmbodiedScan/issues/40#issuecomment-2058598322). Please follow the comment and try again.此问题的触发原因与[此](https://github.com/OpenRobotLab/EmbodiedScan/issues/40#issuecomment-2058598322)类似。请按照评论重试。

I did not solve the problem according to your suggestion. The error is still the same.
