### ISSUE TITLE
[Docs] Calculation of 3D IoU-based average precision (AP) 

### ISSUE THREAD

**Issue by LZ-CH** [OpenRobotLab/EmbodiedScan#61]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

Hi, I noticed that when calculating the 3D IoU-based average precision (AP) with thresholds of 0.25 and 0.5, the box with the top-10 score is selected as the prediction box to be measured. Why is 10 chosen instead of 1?

The code from [embodiedscan/eval/metrics/grounding_metric.py: Line 103-106](https://github.com/OpenRobotLab/EmbodiedScan/blob/044508b05fc381cbb10e16d2868d4559e623b4de/embodiedscan/eval/metrics/grounding_metric.py#L103):

```python            
box_index = target_scores.argsort(dim=-1, descending=True)[:10]
top_bbox = bboxes[box_index]

iou = top_bbox.overlaps(top_bbox, gt_bboxes)  # (num_query, 1)
```

**Comment by Tai-Wang** [comment]
Good observation. This is a legacy issue, and we simply follow the convention in the [implementation](https://github.com/nickgkan/butd_detr/blob/main/src/grounding_evaluator.py) of BUTD-DETR. However, it simplifies the task significantly and may not reflect the real performance of the grounding model. We are studying more suitable metric designs and will release a new version together with the release of MMScan.

**Comment by LZ-CH** [comment]
Thank you for your detailed answer. I have carefully looked at the source code of BUTD-DETR. It uses a [k](https://github.com/nickgkan/butd_detr/blob/main/src/grounding_evaluator.py#L163) to control the calculation of top-1\5\10 results respectively. The original paper points out that in the grounding task, the top-1 accuracy is used unless otherwise specified. 

This is the original description from page 10 of the original BUTD-DETR paper:[BUTD-DETR's paper Page10](https://arxiv.org/pdf/2112.08879) "We show quantitative results of our models against previous works in Table 1. We use top-1 accuracy metric, which measures the percentage of times we can find the target box with an IoU higher than the threshold. We report results with IoU@0.25 on SR3D and NR3D; and with both IoU@0.25 and IoU@0.5 on ScanRefer. Please refer to supplementary for more detailed results." 

I hope the above information can help you with subsequent version releases.

**Comment by Tai-Wang** [comment]
Yes, we found it is a problem when adapting the metric for our benchmark, and the current metric is indeed much easier than traditional ones. We are studying this gap and will make a connection between previous benchmarks and metrics and ours in subsequent versions. Thanks for your feedback.
