### ISSUE TITLE
[Bug] 'SparseFeatureFusion3DGrounder is not in the mmengine

### ISSUE THREAD

**Issue by Fan123456-c** [OpenRobotLab/EmbodiedScan#63]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

--

### Reproduces the problem - code sample

python -m torch.distributed.launch tools/train.py configs/grounding/mv-grounding_8xb12_embodiedscan-vg-9dof-full.py --work-dir=work_dirs/mv-3ddet

### Reproduces the problem - command or script

when I started code with python -m torch.distributed.launch tools/train.py configs/grounding/mv-grounding_8xb12_embodiedscan-vg-9dof-full.py --work-dir=work_dirs/mv-3ddet. 
It showed:

### Reproduces the problem - error message

07/31 16:03:31 - mmengine - WARNING - Failed to import `None.registry` make sure the registry.py exists in `None` package.
07/31 16:03:31 - mmengine - WARNING - Failed to search registry with scope "embodiedscan" in the "vis_backend" registry tree. As a workaround, the current "vis_backend" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "embodiedscan" is a correct scope, or whether the registry is initialized.
07/31 16:03:33 - mmengine - WARNING - Failed to search registry with scope "embodiedscan" in the "model" registry tree. As a workaround, the current "model" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "embodiedscan" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 131, in main
    runner = Runner.from_cfg(cfg)
  File "/slurm-files/lfan/env/embo/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/slurm-files/lfan/env/embo/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/slurm-files/lfan/env/embo/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/slurm-files/lfan/env/embo/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/slurm-files/lfan/env/embo/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/slurm-files/lfan/env/embo/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'SparseFeatureFusion3DGrounder is not in the mmengine::model registry. Please check whether the value of `SparseFeatureFusion3DGrounder` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by Fan123456-c** [comment]
And there is other question: when I install MinkowskiEngine, it showed:Collecting git+https://github.com/NVIDIA/MinkowskiEngine
Cloning https://github.com/NVIDIA/MinkowskiEngine to /tmp/pip-req-build-cuwbv0yy
Resolved https://github.com/NVIDIA/MinkowskiEngine to commit 02fc608bea4c0549b0a7b00ca1bf15dee4a0b228
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: MinkowskiEngine
Building wheel for MinkowskiEngine (setup.py): started
Building wheel for MinkowskiEngine (setup.py): finished with status 'error'
Running setup.py clean for MinkowskiEngine
Failed to build MinkowskiEngine
Installing collected packages: MinkowskiEngine
Running setup.py install for MinkowskiEngine: started
Running setup.py install for MinkowskiEngine: finished with status 'error'

**Comment by mxh1999** [comment]
@Fan123456-c You can follow the the [installation guidance](https://github.com/NVIDIA/MinkowskiEngine?tab=readme-ov-file#installation) of MinkowskiEngine.

**Comment by Tai-Wang** [comment]
Close due to inactivity. Please feel free to reopen it if there are any new questions.
