### ISSUE TITLE
[Docs] Annotations for Monocular 3D Perception

### ISSUE THREAD

**Issue by chanhee-luke** [OpenRobotLab/EmbodiedScan#64]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

Hi, is the annotations for Monocular 3D Perception as referred to in the paper available to the public? I don't see the annotations in the data currently provided. Thanks!

-Luke

**Comment by mxh1999** [comment]
We provide `visible_instance_ids` and `visible_occupancy_masks` for each image. It's easy to construct Monocular setting using these masks.

**Comment by chanhee-luke** [comment]
Thanks! How do I get the visible_occupancy_masks for each image? Can you guide me on how to extract each one from occupancy annotations? I tried looking at the annotations and it was a little confusing.

**Comment by mxh1999** [comment]
Following the [guidance](https://github.com/OpenRobotLab/EmbodiedScan/blob/main/data/README.md), you can find `visible_occupancy.pkl` for each scene. It is a list of `visible_occupancy_annotation` which contains the `img_path` and corresponding `visible_occupancy`.

**Comment by chanhee-luke** [comment]
Hi, I'm the .pkl file seems to contain an array size of (40, 40, 16) (for matterport3d) for each image. How should I match each image pixel's occupancy with the array?

**Comment by mxh1999** [comment]
It seems that there's a misunderstanding about the definition of `occupancy`. Following [TPVFormer](https://github.com/wzzheng/TPVFormer), our `occupancy` is the semantic labels of dense voxels in 3D space.
