### ISSUE TITLE
[Feature] Code for occupancy generation.

### ISSUE THREAD

**Issue by LinShan-Bin** [OpenRobotLab/EmbodiedScan#69]
### Code for occupancy generation

The resolution of the provided occupancy labels is currently set at 40x40x16, which we've found to be insufficient for certain applications. Could you please provide the source code for generating these labels, allowing us to modify the resolution to better suit our specific needs?

**Comment by LinShan-Bin** [comment]
Many thanks for your quick reply and awesome work!

**Comment by chenhaomingbob** [comment]
Hi, thanks for your wonderful work!
Could you provide occupancy generation source codes for other datasets, like Matterport3D, allowing us to modify the resolution?

**Comment by mxh1999** [comment]
@chenhaomingbob 
[HERE](https://drive.google.com/drive/folders/1VeQqm92UL4FgTGBcv2AAikCD6L2POJ01?usp=sharing) is the script to generate occupancy labels for Matterport3D. `mp3d_category_mapping.tsv` can be downloaded from matterport3d official github page. `scannet_infos_train_MDJH_full_10_visible.pkl` is the early version of Embodiedscan annotations, you can use released Embodiedscan annotations.

**Comment by zhuhu00** [comment]
Regarding the data generation of Matterport3D, I have some questions about file details: For example, how to obtain files like `/mnt/petrelfs/share_data/maoxiaohan/3rscan_data/data_1023/aligned_matterport3d`, `/mnt/petrelfs/share_data/maoxiaohan/matterport3d/meta_data/test.txt`, and `/mnt/petrelfs/share_data/maoxiaohan/matterport3d/meta_data/scene_mapping.json` ?
