### ISSUE TITLE
[Docs] Test for multi-view 3d detection

### ISSUE THREAD

**Issue by linxuewu** [OpenRobotLab/EmbodiedScan#70]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

How to evaluate the model's performance on the multi-view 3D detection test dataset? [The test server](https://huggingface.co/spaces/AGC2024/visual-grounding-2024) only support 3d grounding task.

**Comment by mxh1999** [comment]
We will build a server to support detection and other tasks in the future.
