### ISSUE TITLE
[Docs] Confusion about metrics

### ISSUE THREAD

**Issue by linxuewu** [OpenRobotLab/EmbodiedScan#72]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

I found that there seems to be an issue with the [code](https://github.com/OpenRobotLab/EmbodiedScan/blob/main/embodiedscan/eval/indoor_eval.py#L322) related to average recall; it seems to be calculating max recall instead of average recall?

**Comment by mxh1999** [comment]
The average recall here means the average of recalls over categories.

**Comment by linxuewu** [comment]
This metric is not suitable for evaluating  detector's performance, because it increases monotonically with the number of proposals.

**Comment by mxh1999** [comment]
So we use AP as our detection metrics.

**Comment by RuiyuanLyu** [comment]
Indeed, the Recall Metric increases monotonically with the number of proposals, as this is the inherent nature of Recall. Consequently, focusing solely on the Recall Metric is not sufficient for evaluating the performance of a detector. Therefore, it is suggested to consider the AP in conjunction with the Recall Metric. Actually, we report AP as our primary detection metric in the EmbodiedScan paper.

**Comment by linxuewu** [comment]
I think this metric might be a bit distracting for the readers, so I'd suggest removing it.

But, it's not a big deal if keep it.
