### ISSUE TITLE
[Docs] ARKit Scenes Processing Instructions

### ISSUE THREAD

**Issue by chanhee-luke** [OpenRobotLab/EmbodiedScan#74]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

Hi, thanks for releasing EmbodiedScan V2 with ArKitScenes! Will the Readme under data section be updated with information on processing ArkitScenes? Looking forward to using your annotations. Thanks again!

- Luke

**Comment by mxh1999** [comment]
We have updated the README under data section.
Please download the `3dod` part of the Arkitscenes and try EmbodiedScanv2!
