### ISSUE TITLE
[Docs] The image number in `embodiedscan_infos_train.pkl` is not consistent with the actual image count.

### ISSUE THREAD

**Issue by zd11024** [OpenRobotLab/EmbodiedScan#77]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

Hi, thanks for your nice work!

I noticed that the image number in `embodiedscan_infos_train.pkl` is not always consistent with the actual image count. For example, there are 98 images for the scan `scene0000_01` from  `embodiedscan_infos_train.pkl`. But the actual RGB-D video contains ~1540 frames, resulting 155 frames after downsampling. After comparing the two sequences, I noticed that some frames are missing, making the sequence not a continuous sequence. Could you please clarify why some frames were dropped? 

Look forward to your feedback!

**Comment by mxh1999** [comment]
Their camera poses are missing.
See [this issue](https://github.com/ScanNet/ScanNet/issues/9) for details.
