### ISSUE TITLE
[Bug] No 'embodiedscan_test_vg_all.json' file

### ISSUE THREAD

**Issue by Fan123456-c** [OpenRobotLab/EmbodiedScan#80]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

/

### Reproduces the problem - code sample

mv-grounding_8xb12_embodiedscan-vg-9dof_complex-all.py

### Reproduces the problem - command or script

![image](https://github.com/user-attachments/assets/a430b4cd-4565-4b5a-98d5-452f5d38ae8a)

### Reproduces the problem - error message

When I use congfig file: mv-grounding_8xb12_embodiedscan-vg-9dof_complex-all.py, in test_dataloader , it needs vg_file='embodiedscan_test_vg_all.json', but there is no such file in embodiedscan dataset, only have embodiedscan_test_vg.json file

**Comment by henryzhengr** [comment]
TDLR: you can probably just use embodiedscan_test_vg.json for test_dataloader

I think the authors used the suffix "_all" to denote the data samples containing complex prompt. At least in the setting in the readme, having complex prompt during evaluation doesnt really affect the performance, it only matters during training. So you can just use the embodiedscan_test_vg.json file in this case.

**Comment by Fan123456-c** [comment]
> TDLR: you can probably just use embodiedscan_test_vg.json for test_dataloader
> 
> I think the authors used the suffix "_all" to denote the data samples containing complex prompt. At least in the setting in the readme, having complex prompt during evaluation doesnt really affect the performance, it only matters during training. So you can just use the embodiedscan_test_vg.json file in this case.

Thank you for your attention. In the log file provided by the authors (https://download.openmmlab.com/mim-example/embodiedscan/mv-grounding-full.log), it shows that the embodiedscan_test_vg_all.json file was used. Why is that?
![Uploading confuse.png…]()

**Comment by Fan123456-c** [comment]
> TDLR: you can probably just use embodiedscan_test_vg.json for test_dataloader
> 
> I think the authors used the suffix "_all" to denote the data samples containing complex prompt. At least in the setting in the readme, having complex prompt during evaluation doesnt really affect the performance, it only matters during training. So you can just use the embodiedscan_test_vg.json file in this case.

Thank you for your attention. In the log file provided by the authors (https://download.openmmlab.com/mim-example/embodiedscan/mv-grounding-full.log), it shows that the embodiedscan_test_vg_all.json file was used. Why is that?
<img width="380" alt="confuse" src="https://github.com/user-attachments/assets/6e7a6989-1c13-49ed-b3ab-7edf26c99dcd">

**Comment by mxh1999** [comment]
We renamed the annotation files before publishing, but forgot to change the corresponding config files.
I'm sorry for this fault.

**Comment by Fan123456-c** [comment]
Thank you for your attention. That's OK, and could you take a look at another question I have posed? [https://github.com/OpenRobotLab/EmbodiedScan/issues/81](url)

**Comment by Fan123456-c** [comment]
Thank you for your attention. That's OK, and could you take a look at another question I have posed? [https://github.com/OpenRobotLab/EmbodiedScan/issues/81](url)

> We renamed the annotation files before publishing, but forgot to change the corresponding config files. I'm sorry for this fault.

**Comment by Fan123456-c** [comment]
Thank you for your attention. That's OK, and could you take a look at another question I have posed? [81](https://github.com/OpenRobotLab/EmbodiedScan/issues/81)
