### ISSUE TITLE
[Docs] question about Multi-View 3D Visual Grounding metric

### ISSUE THREAD

**Issue by Fan123456-c** [OpenRobotLab/EmbodiedScan#81]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

I am confused about the accuracy of the model(Multi-view 3D visual grounding) you submitted：
In your paper, it shows: 
![image](https://github.com/user-attachments/assets/a1e1276f-b336-4b39-8791-ce3c925e067c)
but in github web, it shows:
![image](https://github.com/user-attachments/assets/c8084f9c-8b2a-45c4-b031-e97233be8b6d)
So if I reproduce your 3D grounding-full model, which benchmark should the accuracy I obtain be compared to?

**Comment by Tai-Wang** [comment]
You can directly refer to the latest results shown in the GitHub repo. We will consider updating the results in the paper during polishing the EmbodiedScan and MMScan benchmarks in the following months.
