### ISSUE TITLE
[Docs] Test metrics

### ISSUE THREAD

**Issue by linxuewu** [OpenRobotLab/EmbodiedScan#83]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

Could you provide the visual grounding metrics of your model on the test dataset? It would be helpful for reference. Thank you.

**Comment by Tai-Wang** [comment]
Please refer to the [explanation](https://github.com/OpenRobotLab/EmbodiedScan?tab=readme-ov-file#inference-and-submit-your-results) provided in the README.
