### ISSUE TITLE
[Feature] The entire MMScan dataset release 

### ISSUE THREAD

**Issue by SiyuanWei** [OpenRobotLab/EmbodiedScan#84]
### What is the feature?

The entire MMScan dataset release

### Any other context?

Amazing work, when will the entire MMscan dataset be released?

**Comment by rbler1234** [comment]
The beta version of MMScan is available in this [form](https://docs.google.com/forms/d/e/1FAIpQLScUXEDTksGiqHZp31j7Zp7zlCNV7p_08uViwP_Nbzfn3g6hhw/viewform) (under `embodiedscan-v2/MMScan-beta`), including all VG/QA/Caption samples and meta-annotation of 3RScan/scannet/matterport3d ( ArkitScene is not included and will be added at a later date ). In addition, our MMScan code will be released these days. We have developed an MMScan API to facilitate dataset loading and model evaluation.
