### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Germany321** [OpenRobotLab/EmbodiedScan#90]
### What is the feature?

I reviewed the raw data file `embodiedscan_infos_train.pkl` but could not find a mapping between the object IDs and the 3D bounding boxes. However, the caption and QA data both reference the object IDs. Could the authors provide instructions on how to establish this mapping?

**Comment by rbler1234** [comment]
In the pkl file, "data_list" stores information for all scenes. For each scene, data["data_list"][scan_id]["instances"] contains a list of information about all objects, where each object is represented as a dictionary with the following keys:
- 'bbox_3d': The 9 DoF bounding box of the object.
- 'bbox_id': **The ID of the object.**
- 'bbox_label_3d': The category label of the object.

An example code to get all these information is:
```python
with open(path, 'rb') as f:
    data = np.load(f, allow_pickle=True)

metainfo = data['metainfo']
object_type_to_int = metainfo['categories']
object_int_to_type = {v: k for k, v in object_type_to_int.items()}

datalist = data['data_list']
for scene_idx in range(len(datalist)):
    scene_id = datalist[scene_idx]['sample_idx'] # The ID of the scan
    instances = datalist[scene_idx]['instances']
# processing the object information
for _idx in range(len(instances)):
    object_bbox = instances[_idx]['bbox_3d']  # The 9 DoF bounding box of the object.
    bbox_label_3d = instances[_idx]['bbox_label_3d']  # int
    object_id = instances[_idx]['bbox_id']  # The ID of the object.
    object_type = object_int_to_type[bbox_label_3d] # The category label of the object.
...
```
